---
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create directories for Radarr
  file:
    path: "{{ item }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: "0755"
  loop:
    - "{{ radarr_config }}"
    - "{{ radarr_nginx_config }}"
    - "{{ movies_path }}"
    - "{{ downloads_path }}"

- name: Create Nginx config file from template
  template:
    src: templates/radarr.nginx.conf.j2
    dest: "{{ radarr_nginx_config }}/nginx.conf"

- name: Deploy Radarr container
  docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:latest
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "GB"
    volumes:
      - "{{ radarr_config }}:/config"
      - "{{ movies_path }}:/movies"
      - "{{ downloads_path }}:/downloads"
    ports:
      - "7878:7878"
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "radarr"
    networks:
      - name: media_network
    restart_policy: unless-stopped
    state: started


- name: Wait for Radarr to be ready
  wait_for:
    port: 7878
    timeout: 15

- name: Start radarr_nginx container
  docker_container:
    name: radarr_nginx
    image: nginx:latest
    volumes:
      - "{{ radarr_nginx_config }}/nginx.conf:/etc/nginx/nginx.conf"
      - "{{ ssl_cert_dir }}/server.crt:/etc/nginx/ssl/server.crt"
      - "{{ ssl_cert_dir }}/server.key:/etc/nginx/ssl/server.key"
    ports:
      - "{{ radarr_port }}:443"
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "radarr_nginx"
    networks:
      - name: media_network
    restart_policy: unless-stopped
    state: started

- name: Radarr deployed
  debug:
    msg: "Radarr is running successfully"
