---
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create directories for NZBget
  file:
    path: "{{ item }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: "0755"
  loop:
    - "{{ nzbget_config }}"
    - "{{ nzbget_nginx_config }}"
    - "{{ downloads_path }}"

- name: Create Nginx config file from template
  template:
    src: templates/nzbget.nginx.conf.j2
    dest: "{{ nzbget_nginx_config }}/nginx.conf"

- name: Deploy NZBGet container
  docker_container:
    name: nzbget
    image: lscr.io/linuxserver/nzbget:latest
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "GB"
      NZBGET_USER: "{{ nzbget_username }}"
      NZBGET_PASS: "{{ nzbget_password }}"
    volumes:
      - "{{ nzbget_config }}:/config"
      - "{{ downloads_path }}:/downloads"
    ports:
      - "6789:6789"
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "nzbget"
    networks:
      - name: media_network
    restart_policy: unless-stopped
    state: started


- name: Wait for NZBget to be ready
  wait_for:
    port: 6789
    timeout: 15

- name: Start nzbget_nginx container
  docker_container:
    name: nzbget_nginx
    image: nginx:latest
    volumes:
      - "{{ nzbget_nginx_config }}/nginx.conf:/etc/nginx/nginx.conf"
      - "{{ ssl_cert_dir }}/server.crt:/etc/nginx/ssl/server.crt"
      - "{{ ssl_cert_dir }}/server.key:/etc/nginx/ssl/server.key"
    ports:
      - "{{ nzbget_port }}:443"
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "nzbget_nginx"
    networks:
      - name: media_network
    restart_policy: unless-stopped
    state: started

- name: NZBget deployed
  debug:
    msg: "NZBget is running successfully"
