---
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create directories for Radarr
  file:
    path: "{{ item }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: "0755"
  loop:
    - "{{ radarr_config }}"
    - "{{ movies_path }}"
    - "{{ downloads_path }}"

- name: Deploy Radarr container
  docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:latest
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "GB"
    volumes:
      - "{{ radarr_config }}:/config"
      - "{{ movies_path }}:/movies"
      - "{{ downloads_path }}:/downloads"
    ports:
      - "{{ radarr_port }}:7878"
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "radarr"
    restart_policy: unless-stopped
    state: started

- name: Radarr deployed
  debug:
    msg: "Radarr is running successfully"
