---
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create directories for Sonarr
  file:
    path: "{{ item }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: "0755"
  loop:
    - "{{ sonarr_config }}"
    - "{{ sonarr_nginx_config }}"
    - "{{ tvseries_path }}"
    - "{{ downloads_path }}"

- name: Create Nginx config file from template
  template:
    src: templates/sonarr.nginx.conf.j2
    dest: "{{ sonarr_nginx_config }}/nginx.conf"

- name: Deploy Sonarr container
  docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "GB"
    volumes:
      - "{{ sonarr_config }}:/config"
      - "{{ tvseries_path }}:/tv"
      - "{{ downloads_path }}:/downloads"
    ports:
      - "8989:8989"
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "sonarr"
    restart_policy: unless-stopped
    state: started


- name: Wait for Sonarr to be ready
  wait_for:
    port: 8989
    timeout: 15

- name: Start sonarr_nginx container
  docker_container:
    name: sonarr_nginx
    image: nginx:latest
    volumes:
      - "{{ sonarr_nginx_config }}/nginx.conf:/etc/nginx/nginx.conf"
      - "{{ ssl_cert_dir }}/server.crt:/etc/nginx/ssl/server.crt"
      - "{{ ssl_cert_dir }}/server.key:/etc/nginx/ssl/server.key"
    ports:
      - "{{ sonarr_port }}:443"
    labels:
      com.docker.compose.project: "media_stack"
      com.docker.compose.service: "sonarr_nginx"
    restart_policy: unless-stopped
    state: started

- name: Sonarr deployed
  debug:
    msg: "Sonarr is running successfully"
