---
- name: Unmount ISO image on CD-ROM
  community.general.proxmox_disk:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    vmid: "{{ vm_id }}"
    name: "{{ vm_name }}"
    disk: ide2
    media: cdrom
    iso_image: "{{ iso_storage }}:iso/{{ iso_image }}"
    state: absent