---
# - name: Update and generate SSL files
#   hosts: nasvm
#   become: true
#   gather_facts: false

#   roles:
#     # - basics
#     - openssl_generate_certificate

# - name: Install docker
#   hosts: nasvm
#   become: true
#   gather_facts: yes

#   roles:
#     - docker

- name: Install Portainer, Nextcloud, Nginx
  hosts: nasvm
  become: true
  gather_facts: false

  roles:
    # - install_portainer
    # - install_nextcloud
    # - install_immich
    - install_nginx_proxy_manager
    # - cloudflare_tunnel

