---
# - name: Update and generate SSL files
#   hosts: pvehomelab
#   become: true
#   gather_facts: false

#   roles:
#     - basics
#     - openssl_generate_certificate

# - name: Install docker
#   hosts: pvehomelab
#   become: true
#   gather_facts: yes

#   roles:
#     - docker

- name: Install Portainer, Nextcloud, Nginx
  hosts: pvehomelab
  become: true
  gather_facts: false

  roles:
    # - install_tsdproxy_tailscale
    # - install_homarr
    # - install_portainer
    # - install_nextcloud
    # - install_immich
    - install_syncthing
    # - install_media_packages
    # - cloudflare_tunnel

