---
# - name: Setup after new install
#   hosts: nasvm
#   become: true
#   gather_facts: yes

#   roles:
#     - basics
#     - docker

# - name: Install Portainer, Nextcloud, Nginx
#   hosts: nasvm
#   gather_facts: false

#   roles:
#     - install_portainer
#     - install_nextcloud
#     - install_nginx_proxy_manager

- name: Install Cloudflare
  hosts: nasvm
  become: true
  gather_facts: false

  roles:
    - cloudflare_tunnel
