---
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create Syncthing directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: "0755"
  loop:
    - "{{ syncthing_config }}"
    - "{{ syncthing_data1 }}"
    - "{{ syncthing_data2 }}"

- name: Deploy Syncthing container
  docker_container:
    name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    hostname: syncthing
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "GB"
    volumes:
      - "{{ syncthing_config }}:/config"
      - "{{ syncthing_data1 }}:/data1"
      - "{{ syncthing_data2 }}:/data2"
    ports:
      - "{{ syncthing_port }}:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart_policy: unless-stopped
    state: started

- name: Syncthing deployed
  debug:
    msg: "Syncthing is running successfully"

