--- 
- name: Create new disk in VM (do not rewrite in case it exists already)
  community.general.proxmox_disk:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    vmid: "{{ vm_id }}"
    name: "{{ vm_name }}"
    disk: scsi0
    backup: true
    cache: none
    storage: "{{ vm_storage }}"
    size: "{{ vm_disk_size }}"
    state: present
