---
- name: Remove repo
  file:
    path: /etc/apt/sources.list.d/{{ repo_to_remove1 }}.list
    state: absent

- name: Remove ceph enterprise repo
  file:
    path: /etc/apt/sources.list.d/{{ repo_to_remove2 }}.list
    state: absent

- name: Enable the No-Subscription repository
  copy:
    dest: /etc/apt/sources.list.d/{{ repo_to_add }}.list
    content: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    mode: '0644'

- name: Update packages
  apt:
    update_cache: true
    upgrade: true
