---
- name: Update /etc/logind.conf file to ignore lid close
  lineinfile:
    dest: /etc/systemd/logind.conf
    regexp: "^#?HandleLidSwitch=.*"
    line: "HandleLidSwitch=ignore"
    state: present
  become: true
  notify: Restart systemd-logind

- name: Create a systemd script to turn off display on lid close
  copy:
    dest: /etc/systemd/system/display_off_on_lid_close.service
    content: |
      [Unit]
      Description=Turn off display on lid close

      [Service]
      ExecStart=/usr/bin/xset dpms force off

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  become: true
  notify: Enable and start the display off service
  
