---
- name: Restart systemd-logind
  systemd:
    name: systemd-logind
    state: restarted
  become: true

- name: Enable and start the display off service
  systemd:
    name: display_off_on_lid_close.service
    enabled: true
    state: started
  become: true
